In [1]:
import xarray as xr # To create a Dataset
import pickle       # To save Dataset to memory

In [2]:
from aqua import Reader, catalogue
import sys
sys.path.insert(0, '../')
from src.trop_prec_diagnostic import TR_PR_Diagnostic as TR_PR_Diag

In [9]:
reader = Reader(model="IFS", exp="tco2559-ng5", source="ICMGG_atm2d", regrid="r010")
ifs = reader.retrieve(regrid=True)

In [4]:
diag = TR_PR_Diag(trop_lat = 10,  num_of_bins = 15, first_edge = 0, width_of_bin = 1*10**(-6)/15)

## To make the test very fast, loading only one timestep

In [20]:
chunk_1  = reader.retrieve(streaming=True, stream_step =1, regrid=True )
chunk_2  = reader.retrieve(streaming=True, stream_step =1, regrid=True)
chunk_3  = reader.retrieve(streaming=True, stream_step =1, regrid=True)

In [21]:
chunk_1

<xarray.Dataset>
Dimensions:    (time: 1, lat: 1800, lon: 3600, level: 5)
Coordinates:
  * time       (time) datetime64[ns] 2020-01-20T05:00:00
  * lat        (lat) float64 -89.95 -89.85 -89.75 -89.65 ... 89.75 89.85 89.95
  * lon        (lon) float64 0.0 0.1 0.2 0.3 0.4 ... 359.6 359.7 359.8 359.9
  * level      (level) int64 1 2 3 4 5
Data variables: (12/81)
    100si      (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    100u       (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    100v       (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    10u        (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    10v        (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    2d         (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    ...         ...
    uvb        (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    vike       (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    vipie      (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    vipile     (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    vithe      (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
    z          (time, lat, lon) float64 dask.array<chunksize=(1, 1800, 3600), meta=np.ndarray>
Attributes:
    edition:            1
    centre:             ecmf
    centreDescription:  European Centre for Medium-Range Weather Forecasts
    subCentre:          0
    history:            🪄🧙‍♂️🔮 magic dataset assembly provided by gribscan.IF...

#### For one week, calculations are about 100 times slower.

In [46]:
#week_1  = reader.retrieve(streaming=True, stream_unit = 'weeks', regrid=True )
#week_2  = reader.retrieve(streaming=True, stream_unit = 'weeks', regrid=True)
#week_3  = reader.retrieve(streaming=True, stream_unit = 'weeks', regrid=True)

In [ ]:
#week_1

##  Chunk #1

#### Counts-histogram of tropical precipitaion

In [22]:

hist_ifs_week_1  = diag.hist1d_fast(chunk_1)
hist_ifs_week_1

<xarray.DataArray (left_edge: 15)>
array([6.79336e+05, 1.25250e+04, 6.02900e+03, 3.89800e+03, 2.72100e+03,
       1.99400e+03, 1.51000e+03, 1.20900e+03, 9.88000e+02, 8.19000e+02,
       6.82000e+02, 5.54000e+02, 5.24000e+02, 4.53000e+02, 4.25000e+02])
Coordinates:
  * left_edge  (left_edge) float64 0.0 6.667e-08 ... 8.667e-07 9.333e-07
    width      (left_edge) float64 6.667e-08 6.667e-08 ... 6.667e-08 6.667e-08
Attributes: (12/23)
    paramId:                    172228
    dataType:                   fc
    numberOfPoints:             26306560
    typeOfLevel:                surface
    stepUnits:                  1
    stepType:                   instant
    ...                         ...
    target_units:               m s**-1
    factor:                     0.0002777777777777778
    offset:                     0
    decumulated:                1
    src_units:                  m
    units_fixed:                1

#### Creating the Dataset with global attributes

In [23]:
tprate_dataset_1 = hist_ifs_week_1.to_dataset(name="trop_counts")
tprate_dataset_1.attrs = ifs.attrs

#### Storing into memory

In [24]:
path = '.'
with open(str(path)+'ifs_dataset_1.pickle', 'wb') as output:
    pickle.dump(tprate_dataset_1, output)

## Chunk #2

#### Counts-histogram of tropical precipitaion

In [25]:

hist_ifs_week_2  = diag.hist1d_fast(chunk_2)
hist_ifs_week_2

<xarray.DataArray (left_edge: 15)>
array([6.75214e+05, 1.31170e+04, 6.53000e+03, 4.23100e+03, 2.82800e+03,
       2.12900e+03, 1.57300e+03, 1.26900e+03, 1.00200e+03, 9.19000e+02,
       7.91000e+02, 6.78000e+02, 5.92000e+02, 5.01000e+02, 4.95000e+02])
Coordinates:
  * left_edge  (left_edge) float64 0.0 6.667e-08 ... 8.667e-07 9.333e-07
    width      (left_edge) float64 6.667e-08 6.667e-08 ... 6.667e-08 6.667e-08
Attributes: (12/23)
    paramId:                    172228
    dataType:                   fc
    numberOfPoints:             26306560
    typeOfLevel:                surface
    stepUnits:                  1
    stepType:                   instant
    ...                         ...
    target_units:               m s**-1
    factor:                     0.0002777777777777778
    offset:                     0
    decumulated:                1
    src_units:                  m
    units_fixed:                1

#### Creating the Dataset with global attributes

In [26]:
tprate_dataset_2 = hist_ifs_week_2.to_dataset(name="trop_counts")
tprate_dataset_2.attrs = ifs.attrs

#### Storing into memory

In [32]:
path = '.'
with open(str(path)+'ifs_dataset_2.pickle', 'wb') as output:
    pickle.dump(tprate_dataset_2, output)

## Chunk #3

#### Counts-histogram of tropical precipitaion

In [28]:

hist_ifs_week_3  = diag.hist1d_fast(chunk_3)
hist_ifs_week_3

<xarray.DataArray (left_edge: 15)>
array([6.72319e+05, 1.32330e+04, 6.53300e+03, 4.29100e+03, 3.00700e+03,
       2.18100e+03, 1.79800e+03, 1.46100e+03, 1.21000e+03, 1.02000e+03,
       8.47000e+02, 7.72000e+02, 6.84000e+02, 6.69000e+02, 5.56000e+02])
Coordinates:
  * left_edge  (left_edge) float64 0.0 6.667e-08 ... 8.667e-07 9.333e-07
    width      (left_edge) float64 6.667e-08 6.667e-08 ... 6.667e-08 6.667e-08
Attributes: (12/23)
    paramId:                    172228
    dataType:                   fc
    numberOfPoints:             26306560
    typeOfLevel:                surface
    stepUnits:                  1
    stepType:                   instant
    ...                         ...
    target_units:               m s**-1
    factor:                     0.0002777777777777778
    offset:                     0
    decumulated:                1
    src_units:                  m
    units_fixed:                1

#### Creating the Dataset with global attributes

In [29]:
tprate_dataset_3 = hist_ifs_week_3.to_dataset(name="trop_counts")
tprate_dataset_3.attrs = ifs.attrs

#### Storing into memory

In [30]:
path = '.'
with open(str(path)+'ifs_dataset_3.pickle', 'wb') as output:
    pickle.dump(tprate_dataset_3, output)

## Reading and Summing

In [34]:
with open(str(path)+'ifs_dataset_1.pickle', 'rb') as data:
    dataset_1 = pickle.load(data)
with open(str(path)+'ifs_dataset_2.pickle', 'rb') as data:
    dataset_2 = pickle.load(data)
with open(str(path)+'ifs_dataset_3.pickle', 'rb') as data:
    dataset_3 = pickle.load(data)

#### Summing histograms for 3 time-chunks

In [35]:
dataset = dataset_1 + dataset_2 + dataset_3

In [36]:
dataset

<xarray.Dataset>
Dimensions:      (left_edge: 15)
Coordinates:
  * left_edge    (left_edge) float64 0.0 6.667e-08 ... 8.667e-07 9.333e-07
    width        (left_edge) float64 6.667e-08 6.667e-08 ... 6.667e-08 6.667e-08
Data variables:
    trop_counts  (left_edge) float64 2.027e+06 3.888e+04 ... 1.623e+03 1.476e+03